"""Native DWF 2D package and legacy-stream parsing for Python."""

from __future__ import annotations

from collections.abc import Sequence
from importlib.metadata import PackageNotFoundError, version

from . import _core
from ._core import DwfError, DwfLimitError, InvalidDwfError, UnsupportedDwfError
from .document import (
    Bounds2D,
    Brush,
    ClipPath,
    ColoredPoint,
    CompositingGroup,
    Drawing,
    Entity,
    EntityQuery,
    GradientBrush,
    GradientStop,
    Image,
    ImageBrush,
    PathFigure,
    PathSegment,
    Point2D,
    RgbaColor,
    Sheet,
    SolidBrush,
    Style,
    UnsupportedBrush,
    VisualBrush,
    read,
    readfile,
)
from .matplotlib import plot, save_plot
from .raw import (
    DEFAULT_LIMITS,
    ArchiveEntry,
    Diagnostic,
    DwfFormatInfo,
    DwfxPackageInfo,
    Interface,
    Manifest,
    OpcContentType,
    OpcRelationship,
    PackageInfo,
    Page,
    PageResource,
    Paper,
    ParseLimits,
    Property,
    Resource,
    Section,
    SourceInfo,
    W2dBlockRef,
    W2dColoredPoint,
    W2dEmbeddedFont,
    W2dEntity,
    W2dFont,
    W2dImage,
    W2dLayer,
    W2dLineStyle,
    W2dPoint,
    W2dRendition,
    W2dSourceSpan,
    W2dStream,
    W2dUnits,
    W2dViewport,
    XpsBrush,
    XpsCanvasGroup,
    XpsClip,
    XpsDocument,
    XpsEntity,
    XpsGlyphs,
    XpsGradientStop,
    XpsImageMetadata,
    XpsOpacityMask,
    XpsPage,
    XpsPathFigure,
    XpsPathGeometry,
    XpsPathSegment,
    XpsSourceSpan,
    XpsStyle,
    decode_w2d,
    detect_format,
    inspect_dwfx,
    inspect_package,
)
from .svg import PaletteColor, render_svg, save_svg

try:
    __version__ = version("ezdwf")
except PackageNotFoundError:  # pragma: no cover - source tree without install
    __version__ = _core.core_version()


def main(argv: Sequence[str] | None = None) -> int:
    """Run the ezdwf command-line interface."""

    from .__main__ import main as cli_main

    return cli_main(argv)


__all__ = [
    "DEFAULT_LIMITS",
    "ArchiveEntry",
    "Bounds2D",
    "Brush",
    "ClipPath",
    "ColoredPoint",
    "CompositingGroup",
    "Diagnostic",
    "Drawing",
    "DwfError",
    "DwfFormatInfo",
    "DwfLimitError",
    "DwfxPackageInfo",
    "Entity",
    "EntityQuery",
    "GradientBrush",
    "GradientStop",
    "Image",
    "ImageBrush",
    "Interface",
    "InvalidDwfError",
    "Manifest",
    "OpcContentType",
    "OpcRelationship",
    "PackageInfo",
    "Page",
    "PageResource",
    "PaletteColor",
    "Paper",
    "ParseLimits",
    "PathFigure",
    "PathSegment",
    "Point2D",
    "Property",
    "Resource",
    "RgbaColor",
    "Section",
    "Sheet",
    "SolidBrush",
    "SourceInfo",
    "Style",
    "UnsupportedBrush",
    "UnsupportedDwfError",
    "VisualBrush",
    "W2dBlockRef",
    "W2dColoredPoint",
    "W2dEmbeddedFont",
    "W2dEntity",
    "W2dFont",
    "W2dImage",
    "W2dLayer",
    "W2dLineStyle",
    "W2dPoint",
    "W2dRendition",
    "W2dSourceSpan",
    "W2dStream",
    "W2dUnits",
    "W2dViewport",
    "XpsBrush",
    "XpsCanvasGroup",
    "XpsClip",
    "XpsDocument",
    "XpsEntity",
    "XpsGlyphs",
    "XpsGradientStop",
    "XpsImageMetadata",
    "XpsOpacityMask",
    "XpsPage",
    "XpsPathFigure",
    "XpsPathGeometry",
    "XpsPathSegment",
    "XpsSourceSpan",
    "XpsStyle",
    "__version__",
    "decode_w2d",
    "detect_format",
    "inspect_dwfx",
    "inspect_package",
    "main",
    "plot",
    "read",
    "readfile",
    "render_svg",
    "save_plot",
    "save_svg",
]
